# Generated by Django 6.0.4 on 2026-07-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_data',
            field=models.TextField(blank=True, help_text='Base64 encoded profile photo for user accounts', null=True),
        ),
    ]
