# Generated by Django 6.0.4 on 2026-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_user_face_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_std',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Class/Std'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10),
        ),
    ]
