# Generated by Django 6.0.4 on 2026-07-28 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_remove_studentprofile_age_studentprofile_class_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='minutes_late',
            field=models.IntegerField(default=0, help_text='Minutes late relative to batch start time'),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default='09:00:00', help_text='Batch start time (e.g. 16:00 for 4:00 PM)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.CharField(choices=[('self_qr', 'Self QR Scan'), ('teacher', 'Teacher')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='face_data',
            field=models.TextField(blank=True, help_text='Deprecated photo data', null=True),
        ),
        migrations.CreateModel(
            name='DailyBatchAttendanceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_locked', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_locks', to='coaching.batch')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'date'), name='unique_batch_daily_lock')],
            },
        ),
    ]
