# Generated by Django 6.0.4 on 2026-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_attendancerecord_minutes_late_batch_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='daily_note',
            field=models.TextField(blank=True, help_text='Daily teacher tip, assignment, or announcement for the batch', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default='09:00:00', help_text='Batch start time (e.g. 19:15 for 7:15 PM)'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='timing',
            field=models.CharField(help_text='e.g. Mon-Wed-Fri 7:15 PM - 8:15 PM', max_length=100),
        ),
    ]
