# Generated by Django 6.0.4 on 2026-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_batch_daily_note_alter_batch_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='individual_note',
            field=models.TextField(blank=True, help_text='Individual homework or custom task assigned to this student', null=True),
        ),
    ]
