# Generated by Django 6.0.4 on 2026-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0006_studentprofile_individual_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, help_text='Last QR info scan timestamp', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_scanned_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of device used to scan QR info', null=True),
        ),
    ]
